-- Ден и Нощ v1.52 — анонимна статистика за админ панела
-- Пуснете целия файл еднократно в Supabase -> SQL Editor -> New query -> Run.
-- Не се записват cookie/visitor ID, IP адрес, user-agent, име, имейл или телефон на посетителя.

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null,
  page_path text not null,
  source text not null default 'direct',
  referrer_host text not null default '',
  label text not null default ''
);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);
create index if not exists analytics_events_event_type_created_at_idx
  on public.analytics_events (event_type, created_at desc);
create index if not exists analytics_events_page_path_created_at_idx
  on public.analytics_events (page_path, created_at desc);

alter table public.analytics_events enable row level security;
revoke all on table public.analytics_events from anon, authenticated;

create or replace function public.record_analytics_event(
  p_event_type text,
  p_page_path text,
  p_source text default 'direct',
  p_referrer_host text default '',
  p_label text default ''
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_type text := left(coalesce(p_event_type,''), 40);
  v_path text := left(coalesce(p_page_path,'/'), 240);
  v_source text := left(coalesce(nullif(p_source,''),'direct'), 120);
  v_host text := left(coalesce(p_referrer_host,''), 160);
  v_label text := left(coalesce(p_label,''), 180);
begin
  if v_type not in ('page_view','phone_click','map_open','faq_open','reviews_open','call_widget_open') then
    return;
  end if;
  if v_path = '' or left(v_path,1) <> '/' then
    v_path := '/';
  end if;
  insert into public.analytics_events(event_type,page_path,source,referrer_host,label)
  values (v_type,v_path,v_source,v_host,v_label);
end;
$$;

revoke all on function public.record_analytics_event(text,text,text,text,text) from public;
grant execute on function public.record_analytics_event(text,text,text,text,text) to anon, authenticated;

create or replace function public.admin_analytics_kpis(p_since timestamptz)
returns table(
  page_views bigint,
  phone_clicks bigint,
  contact_page_views bigint,
  map_opens bigint,
  faq_opens bigint,
  call_widget_opens bigint
)
language sql
security definer
set search_path = public
as $$
  select
    count(*) filter (where event_type='page_view')::bigint,
    count(*) filter (where event_type='phone_click')::bigint,
    count(*) filter (where event_type='page_view' and page_path='/kontakti.html')::bigint,
    count(*) filter (where event_type='map_open')::bigint,
    count(*) filter (where event_type='faq_open')::bigint,
    count(*) filter (where event_type='call_widget_open')::bigint
  from public.analytics_events
  where created_at >= p_since;
$$;

revoke all on function public.admin_analytics_kpis(timestamptz) from public, anon;
grant execute on function public.admin_analytics_kpis(timestamptz) to authenticated;

create or replace function public.admin_analytics_daily(p_since timestamptz)
returns table(day date, page_views bigint, phone_clicks bigint, contact_actions bigint)
language sql
security definer
set search_path = public
as $$
  select
    (created_at at time zone 'Europe/Sofia')::date as day,
    count(*) filter (where event_type='page_view')::bigint as page_views,
    count(*) filter (where event_type='phone_click')::bigint as phone_clicks,
    count(*) filter (where event_type in ('phone_click','map_open','call_widget_open'))::bigint as contact_actions
  from public.analytics_events
  where created_at >= p_since
  group by 1
  order by 1 asc;
$$;

revoke all on function public.admin_analytics_daily(timestamptz) from public, anon;
grant execute on function public.admin_analytics_daily(timestamptz) to authenticated;

create or replace function public.admin_analytics_top_pages(p_since timestamptz, p_limit integer default 10)
returns table(page_path text, views bigint)
language sql
security definer
set search_path = public
as $$
  select page_path, count(*)::bigint as views
  from public.analytics_events
  where created_at >= p_since and event_type='page_view'
  group by page_path
  order by views desc, page_path asc
  limit greatest(1, least(coalesce(p_limit,10), 25));
$$;

revoke all on function public.admin_analytics_top_pages(timestamptz,integer) from public, anon;
grant execute on function public.admin_analytics_top_pages(timestamptz,integer) to authenticated;

create or replace function public.admin_analytics_sources(p_since timestamptz, p_limit integer default 10)
returns table(source text, views bigint)
language sql
security definer
set search_path = public
as $$
  select source, count(*)::bigint as views
  from public.analytics_events
  where created_at >= p_since
    and event_type='page_view'
    and source <> 'internal'
  group by source
  order by views desc, source asc
  limit greatest(1, least(coalesce(p_limit,10), 25));
$$;

revoke all on function public.admin_analytics_sources(timestamptz,integer) from public, anon;
grant execute on function public.admin_analytics_sources(timestamptz,integer) to authenticated;

create or replace function public.admin_analytics_phones(p_since timestamptz)
returns table(phone text, clicks bigint)
language sql
security definer
set search_path = public
as $$
  select coalesce(nullif(label,''),'Неуточнен') as phone, count(*)::bigint as clicks
  from public.analytics_events
  where created_at >= p_since and event_type='phone_click'
  group by 1
  order by clicks desc, phone asc;
$$;

revoke all on function public.admin_analytics_phones(timestamptz) from public, anon;
grant execute on function public.admin_analytics_phones(timestamptz) to authenticated;
